In [1]:
aList = ["John",33,"Toronto",True]
print(aList)

['John', 33, 'Toronto', True]


In [3]:
aList = ["Afdonny Dimas",2020071016,"Desain Analisis Algoritma","9 Sep 2021","Universitas Pembangunan Jaya"]
print(aList)

['Afdonny', 2020071016, 'Desain Analisis Algoritma', '9 Sep 2021', 'Universitas Pembangunan Jaya']


In [4]:
bin_color=['Red','Green','Blue','Yellow']
bin_color[1]

'Green'

In [5]:
aList = ["Afdonny Dimas",2020071016,"Desain Analisis Algoritma","9 Sep 2021","Universitas Pembangunan Jaya"]
aList[1]

2020071016

In [6]:
aList = ["Afdonny Dimas",2020071016,"Desain Analisis Algoritma","9 Sep 2021","Universitas Pembangunan Jaya"]
aList[4]

'Universitas Pembangunan Jaya'

In [8]:
bin_color=['Red','Green','Blue','Yellow']
bin_color[0:3]

['Red', 'Green', 'Blue']

In [9]:
aList = ["Afdonny Dimas",2020071016,"Desain Analisis Algoritma","9 Sep 2021","Universitas Pembangunan Jaya"]
aList[0:3]

['Afdonny Dimas', 2020071016, 'Desain Analisis Algoritma']

In [16]:
bin_color=['Red','Green','Blue','Yellow']
for aColor in bin_color:
  print(aColor + "square")

Redsquare
Greensquare
Bluesquare
Yellowsquare


In [37]:
bin_List = ["Apel","Semangka","Jeruk","Anggur","Melon"]
for aList in bin_List:
  print("Upj " + aList)

Upj Apel
Upj Semangka
Upj Jeruk
Upj Anggur
Upj Melon


In [31]:
bin_color=('Red','Green','Blue','Yellow','Brown')
bin_color[1]

'Green'

In [32]:
bin_color[1:]

('Green', 'Blue', 'Yellow', 'Brown')

In [33]:
bin_Upj=('Universitas','Pembangunan','Jaya')
bin_Upj[1]

'Pembangunan'

In [35]:
bin_Upj

('Universitas', 'Pembangunan', 'Jaya')

In [44]:
my_tuple = ("pertama = 100","kedua = 200,400,600","ketiga = 300","Keempat = 300") 
print(my_tuple[2]) 

ketiga = 300


In [49]:
bin_colors ={"mannual_color":"Yellow","approved_color":"Green","refused_color":"Red"}
print(bin_colors)

{'mannual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [51]:
bin_colors.get("approved_color")

'Green'

In [53]:
bin_colors['approved_color']

'Green'

In [54]:
bin_colors['approved_color']="puprle"
print(bin_colors)

{'mannual_color': 'Yellow', 'approved_color': 'puprle', 'refused_color': 'Red'}


In [55]:
bin_key ={"Nama":"Afdonny Dimas","Nim":"2020071016","Prodi":"Informatika","Universitas":"UPJ"}
print(bin_key)

{'Nama': 'Afdonny Dimas', 'Nim': '2020071016', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


In [56]:
print(bin_key['Nama'])

Afdonny Dimas


In [57]:
print(bin_key.get('Nama'))

Afdonny Dimas


In [58]:
green = {'grass','leaves'}
print(green)

{'grass', 'leaves'}


In [63]:
red = {'bloods','grapes','grapes'}
print(red)

{'grapes', 'bloods'}


In [66]:
red = {'rose','blood','leaves','fire hydrant'}
yellow = {'dandelions','fire hydrant','leaves'}
print(yellow | red)
print(yellow & red)

{'dandelions', 'rose', 'fire hydrant', 'leaves', 'blood'}
{'fire hydrant', 'leaves'}


In [69]:
import pandas as pd
df = pd.DataFrame([
                   ['1','Fares',32,True],
                   ['2','Elena',23,False],
                   ['3','Steven',40,True]])

In [72]:
df.columns=['id','name','age','decision']
df

id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [73]:
df[['name','age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [76]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [77]:
import pandas as pd
df = pd.DataFrame([
                   ['1','Informatika',50,30,20],
                   ['2','Sistem Informasi',50,30,25],
                   ['3','Teknik Sipil',40,30,10]])

In [78]:
df.columns=['No','Prodi','Mahasiswa','Laki-laki','Perempuan']
df

No             Prodi  Mahasiswa  Laki-laki  Perempuan
0  1       Informatika         50         30         20
1  2  Sistem Informasi         50         30         25
2  3      Teknik Sipil         40         30         10

In [90]:
import numpy as np

In [91]:
myMatrix = np.array([[11,12,13],[21,22,23],[31,32,33]])
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [93]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [105]:
class Stack:
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items==[]
  def push(self,item):
    self.items.append(item)
  def pop(self):
    return self.items[len(self.items)-1]
  def size(self):
    return len(self.item)


In [107]:
stack=Stack()
stack.push('Red')
stack.push('Green')
stack.push('Blue')
stack.push('Yellow')

In [108]:
stack.pop()

'Yellow'

In [109]:
stack.isEmpty()

False

In [117]:
class Queue(object):
  def __init__(self):
    self.items=[]
  def isEmpty(self):
      return self.items == []
  def enqueue(self,item):
      self.items.insert(0,item)
  def dequeue(self):
      return self.items.pop()
  def size(self):
      return len(self.items)
queue=Queue()
queue.enqueue('Red')
queue.enqueue('Green')
queue.enqueue('Blue')
queue.enqueue('Yellow')
print(queue.size())
print(queue.dequeue())
print(queue.dequeue())


4
Red
Green
